# model config
model:
  name: "GRU"
  num_layers: 2
  dropout: 0.05
  input_size: 10
  output_size: 1
  hidden_size: 48
  input_len: 144
  output_len: 288
  bias: true
  batch_first: true
  task: "test" # "train" | "test"
  resume_path: "./checkpoints/GRU_train_MSE_Adam_standard_train_sche_WindTurbineDataset_cuda:0_2022-08-10 21:14:24.638540/model_turbine133.pth"

# schedule config
schedule:
  name: "standard_test_sche"

# dataset config
dataset:
  name: "WindTurbineDataset"
  path: "./data"
  file_name: "wtbdata_245days.csv"
  start_col: 3 # the start column of the data
  train_days: 214
  val_days: 16
  test_days: 15
  total_days: 245
  num_turbines: 134
  day_len: 144
  batch_size: 64
  position: false

# checkpoint config
checkpoint:
  path: "./checkpoints"

# device config
device:
  name: "gpu" # "gpu"|"cpu"

is_debug: true






