# model config
model:
  name: "GRU_pos"
  num_layers: 2
  dropout: 0.05
  input_size: 10
  output_size: 1
  hidden_size: 48
  input_len: 1008
  output_len: 1008
  bias: true
  batch_first: true
  task: "test" # "train" | "test"
  resume_path: "./checkpoints/GRU_pos_train_MSE_Adam_standard_train_sche_WindTurbineDataset_cuda:0_2022-08-11 15:43:09.562910/model_turbine133.pth"

# loss config
loss:
  name: "MSE"

# optimizer config
optimizer:
  name: "Adam"
  learning_rate: 0.0001
  lr_adjust: "type1"

# schedule config
schedule:
  name: "standard_test_sche"

# dataset config
dataset:
  name: "WindTurbineDataset"
  path: "./data"
  file_name: "wtbdata_245days.csv"
  start_col: 3 # the start column of the data
  train_days: 214
  val_days: 16
  test_days: 15
  total_days: 245
  num_turbines: 134
  day_len: 144
  batch_size: 64
  position: true
  position_name: "sdwpf_baidukddcup2022_turb_location.CSV"

# checkpoint config
checkpoint:
  path: "./checkpoints"

# device config
device:
  name: "gpu" # "gpu"|"cpu"

is_debug: false






